Update dependency:get command to latest syntax
hazelcast/hazelcast-python-client pull request #642
Opened 2023-08-07 09:57 UTC by JackPGreen

The `python run_tests.py` script cannot be run as it has the same problem as described in https://github.com/hazelcast/hazelcast-cpp-client/pull/1206

2023-08-11 16:16 UTC, mehmettokgoz requested changes
It looks like `-Ddest` is removed after Maven 3.x and script does not downloads JARs inside repo folder so RC fails to start.

2023-08-11 18:50 UTC, mehmettokgoz requested changes

2023-08-11 18:50 UTC, mehmettokgoz commented on start_rc.py
> +        "-Dartifact=" + artifact,
This line is duplicated.
```suggestion
```

2023-08-14 08:28 UTC, ihsandemir approved these changes

2023-08-14 08:55 UTC, mehmettokgoz approved these changes

2023-08-14 09:13 UTC, merged